DROP TABLE IF EXISTS days CASCADE;

CREATE TABLE days (
  id SERIAL PRIMARY KEY NOT NULL,
  date DATE,
  trip_id INTEGER REFERENCES trips(id) ON DELETE CASCADE,
  notes TEXT,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

