import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import TopNavBar from './components/TopNavBar'
import Footer from './components/Footer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Odyssey',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <TopNavBar />
        <div className={inter.className}>{children}</div>
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
